# Generated by Django 4.2.20 on 2025-04-13 16:13

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0278_login_source_add_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('max_rooms', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_definitions', to='pretixbase.event')),
                ('items', models.ManyToManyField(related_name='room_definitions', to='pretixbase.item')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('event', 'name')},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('password', models.CharField(max_length=190)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pretixbase.event')),
                ('room_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pretix_roomsharing.roomdefinition')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('event', 'name')},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderroom', to='pretixbase.order')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderrooms', to='pretix_roomsharing.room')),
            ],
        ),
    ]
