# Generated by Django 4.2.27 on 2025-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_roomsharing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="disable_random_extra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="optout_random_extra",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomdefinition",
            name="extra_capacity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
