# Generated by Django 4.2.17 on 2025-03-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0275_alter_customer_locale_alter_user_locale'),
        ('pretix_roomsharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderroom',
            name='cart_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderroom',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderroom', to='pretixbase.order'),
        ),
    ]
